spring:
  profiles:
    include: api-key
  datasource:
    hikari:
      username: sa
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: 'true'
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
    show_sql: 'true'

  session:
    store-type: jdbc
